name: Marketing Agent CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'  # Daily at 3 AM UTC

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm install
        npm install -g n8n
    
    - name: Run workflow validation tests
      run: |
        npm test
    
    - name: Test N8N workflow imports
      run: |
        npm run test:workflows
    
    - name: Validate compliance templates
      run: |
        npm run test:compliance

  benchmarks:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm install
        npm install -g n8n
    
    - name: Run marketing benchmarks
      run: |
        npm run benchmarks --output=json
    
    - name: Update README badges
      run: |
        node scripts/update-badges.js
    
    - name: Commit badge updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --staged --quiet || git commit -m "Auto-update performance badges [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  n8n-health:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install N8N
      run: npm install -g n8n
    
    - name: Start N8N server
      run: |
        n8n start --tunnel &
        sleep 30
    
    - name: Test N8N API health
      run: |
        curl -f http://localhost:5678/healthz || exit 1
    
    - name: Import cannabis marketing workflows
      run: |
        npm run import:test-workflows
    
    - name: Test workflow execution
      run: |
        npm run test:workflow-execution